INSERT INTO Todo_Table (ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_COMPLETE)
VALUES (10001, 'in28minutes', 'Learn Spring Boot', CURRENT_DATE(), false);

INSERT INTO Todo_Table (ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_COMPLETE)
VALUES (10002, 'in28minutes', 'Learn AWS Now!', CURRENT_DATE(), false);

INSERT INTO Todo_Table (ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_COMPLETE)
VALUES (10003, 'rgardner', 'Learn DevOps', CURRENT_DATE(), false);

INSERT INTO Todo_Table (ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_COMPLETE)
VALUES (10004, 'rgardner', 'Learn Docker', CURRENT_DATE(), false);
